### ISSUE TITLE
Support JUnit5

### ISSUE THREAD

**Issue by SanderSmee** [haasted/TestLogCollectors#3]
Please provide an extension supporting the JUnit5 lifecycle.

**Comment by haasted** [comment]
I'll add it to the roadmap.

**Comment by haasted** [comment]
Support for JUnit 5 is on its way: 3406e8df6bc7f14ea225338a533c3fd0613087d4

**Comment by haasted** [comment]
Release 0.9.0 adds support for JUnit 5. (724b60e27bba3c3107884bc87c5628fe838fc471)
